---------------------------------------
--dofile:

dofile("active\\message.lua")
dofile("active\\SI_active.lua")
dofile("active\\sql_condition.lua")			
dofile("active\\sql_active.lua")
--dofile("active\\vipfuben_wajue.lua")
-- dofile("active\\kf_ranklist.lua")		
---------------------------------------
--self module:

require("Script.active.active_mgr")
require("Script.active.random_pos_conf")
require("Script.active.random_pos_manager")
require("Script.active.time_conf")
require("Script.active.time_proc")
require("Script.active.boss_active")
require('Script.active.fishing')
require('Script.active.yushi')
require('Script.active.wenquan')
require('Script.active.qsls')
require("Script.active.catch_fish")
require("Script.active.hunting")
require("Script.active.faction_monster")
require("Script.active.escort")
require("Script.active.sjzc")
require("Script.active.anonymity_fight")
require("Script.active.task_a")
require("Script.active.lt")
require("Script.active.faction_fight")
require("Script.active.city_fight")
require("Script.active.kf_drx")
require("Script.active.kf_drx_2")
require("Script.active.kf_ranklist")
require("Script.active.kf_ranklist_2")
require("Script.active.kf_ranklist_3")
require("Script.active.kf_plat")
require("Script.active.kf_chongzhi")
require("Script.active.kf_leichong")
require("Script.active.kf_everyday")
require("Script.active.hf_award")
require("Script.active.hf_ranklist")
require("Script.active.show_girl")
require("Script.active.wabao")
require("Script.active.tjbx")
require("Script.active.first_recharge")
require("Script.active.vipfuben_wajue")
require("Script.active.jijin")
--require("Script.active.chunjie")
require("Script.active.plant_tree")
require("Script.active.chunjie_active")




