dofile 'Manor\\Manor_conf.lua'
dofile 'Manor\\Manor_sys.lua'
dofile 'Manor\\Manor_daji.lua'
dofile 'Manor\\Manor_garden.lua'
dofile 'Manor\\Manor_party.lua'
dofile 'Manor\\Manor_garniture.lua'
dofile 'Manor\\Manor_rank.lua'
dofile 'Manor\\Manor_Robbery.lua'
dofile 'Manor\\Manor_Dog.lua'
-- dofile 'Manor\\Manor_tech.lua'
dofile 'Manor\\message.lua'